export const SEARCH_FOCUS = 'Header/SEARCH_FOCUS'
export const SEARCH_BLUR = 'Header/SEARCH_BLUR'
export const CHANGE_LIST = 'Header/CHANGE_LIST'
export const MOUSE_ENTER = 'Header/MOUSE_ENTER'
export const MOUSE_LEAVE = 'Header/MOUSE_LEAVE'
export const CHANGE_PAGE = 'Header/CHANGE_PAGE'